# An action to push templates to coder server

name: Push templates to coder server

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**Dockerfile.*'
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**Dockerfile.*'
  workflow_dispatch:

jobs:
  # Install terraform and validate the templates
  validate:
    needs: get_changed_templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [$(ls -d */ | cut -f1 -d'/')]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: |
          cd ${{ matrix.template }}
          terraform init
      - name: Terraform Validate
        run: |
          cd ${{ matrix }}
          terraform validate

  # this job will if validate is successful
  deploy_template:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [$(ls -d */ | cut -f1 -d'/')]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get short commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Install latest Coder"
        run: |
          curl -L https://coder.com/install.sh | sh
      - name: "Push template"
        run: |
          echo "Pushing ${{ matrix }} to Coder"
          echo "Template name: ${{ CODER_TEMPLATE_NAME }}"
          echo "Template directory: ${{ CODER_TEMPLATE_DIR }}"
  
          coder templates push $CODER_TEMPLATE_NAME --directory $CODER_TEMPLATE_DIR --yes
        env:
          # Consumed by Coder CLI
          CODER_URL: https://gpu.ctar.ml
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
          # Template source & details
          CODER_TEMPLATE_NAME: ${{ matrix.template }}
          CODER_TEMPLATE_DIR: ./${{ matrix.template }}
