# An action to push templates to coder server

name: Push templates to coder server

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**Dockerfile.*'
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**Dockerfile.*'
  workflow_dispatch:

jobs:
  # this job will if validate is successful
  deploy_template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [aihwkit, deeplearning, matlab]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get short commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Install latest Coder"
        run: |
          curl -L https://coder.com/install.sh | sh
      - name: "Push template"
        run: |
          coder templates push ${{ matrix.template }} --directory ./${{ matrix.template }} --yes
        env:
          # Consumed by Coder CLI
          CODER_URL: https://gpu.ctar.ml
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
