# An action to push templates to coder server

name: ubuntu

on:
  push:
    branches:
      - main
    paths:
      - "ubuntu/main.tf"
      - "ubuntu/Dockerfile"
      - ".github/workflows/ubuntu.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "ubuntu/main.tf"
      - "ubuntu/Dockerfile"
      - ".github/workflows/ubuntu.yaml"

  workflow_dispatch:

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest short commit SHA
        id: get_commit_sha
        run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: update coder template
        uses: matifali/update-coder-template@v1
        with:
          CODER_URL: "https://gpu.ctar.ml"
          CODER_TEMPLATE_NAME: "ubuntu"
          CODER_TEMPLATE_DIR: "ubuntu"
          CODER_TEMPLATE_VERSION: ${{ steps.get_commit_sha.outputs.sha_short }}
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
